
[usage]
reportName = "ISR Print report with exapnded student/response info"
activated = true
outputFileName = "./out/system_reports/isrPrintingExpanded.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"EDID" = "StudentPersonal.LocalId"
[[fields]]
"First Name" = "StudentPersonal.PersonInfo.Name.GivenName"
[[fields]]
"Last Name" = "StudentPersonal.PersonInfo.Name.FamilyName"
[[fields]]
"Date of Birth" = "StudentPersonal.PersonInfo.Demographics.BirthDate"
[[fields]]
"Year Level" = "StudentPersonal.MostRecent.TestLevel.Code"
[[fields]]
"Sex" = "StudentPersonal.PersonInfo.Demographics.Sex"
[[fields]]
"Indigenous Status" = "StudentPersonal.PersonInfo.Demographics.IndigenousStatus"
[[fields]]
"LBOTE Status" = "StudentPersonal.PersonInfo.Demographics.LBOTE"
[[fields]]
"Parent 1 School Education" = "StudentPersonal.MostRecent.Parent1SchoolEducationLevel"
[[fields]]
"Parent 1 Non-School Education" = "StudentPersonal.MostRecent.Parent1NonSchoolEducation"
[[fields]]
"Parent 1 Occupation" = "StudentPersonal.MostRecent.Parent1EmploymentType"
[[fields]]
"Parent 2 School Education" = "StudentPersonal.MostRecent.Parent2SchoolEducationLevel"
[[fields]]
"Parent 2 Non-School Education" = "StudentPersonal.MostRecent.Parent2NonSchoolEducation"
[[fields]]
"Parent 2 Occupation" = "StudentPersonal.MostRecent.Parent2EmploymentType"
[[fields]]
"Student LOTE" = "StudentPersonal.PersonInfo.Demographics.LanguageList.Language.0.Code"
[[fields]]
"Parent 1 LOTE" = "StudentPersonal.MostRecent.Parent1Language"
[[fields]]
"Parent 2 LOTE" = "StudentPersonal.MostRecent.Parent2Language"
[[fields]]
"Country of Birth" = "StudentPersonal.PersonInfo.Demographics.CountryOfBirth"
[[fields]]
"Local School Student ID" = "StudentPersonal.LocalId"
[[fields]]
"Diocesan Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==DiocesanStudentId].value"
[[fields]]
"TAA Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==TAAStudentId].value"
[[fields]]
"Platform Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==NAPPlatformStudentId].value"
[[fields]]
"Previous Local School Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==PreviousLocalId].value"
[[fields]]
"Previous Diocesan Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==PreviousDiocesanStudentId].value"
[[fields]]
"Previous TAA Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==PreviousTAAStudentId].value"
[[fields]]
"Previous Platform Student ID" = "StudentPersonal.OtherIdList.OtherId.#[Type==PreviousNAPPlatformStudentId].value"
[[fields]]
"ClassGroup" = "StudentPersonal.MostRecent.ClassCode"
[[fields]]
"Education Support" = "StudentPersonal.EducationSupport"
[[fields]]
"Full Fee Paying Student" = "StudentPersonal.MostRecent.FFPOS"
[[fields]]
"Visa Code" = "StudentPersonal.PersonInfo.Demographics.VisaSubClass"
[[fields]]
"Home Schooled Student" = "StudentPersonal.HomeSchooledStudent"
[[fields]]
"Sensitive" = "StudentPersonal.Sensitive"
[[fields]]
"Address Line 1" = "CalculatedFields.AddressPlaceholder"
[[fields]]
"Address Line 2" = "CalculatedFields.AddressPlaceholder"
[[fields]]
"Locality" = "CalculatedFields.AddressPlaceholder"
[[fields]]
"Postcode" = "CalculatedFields.AddressPlaceholder"
[[fields]]
"State" = "CalculatedFields.AddressPlaceholder"
[[fields]]
"School Code" = "SchoolInfo.LocalId"
[[fields]]
"School Name" = "SchoolInfo.SchoolName"
[[fields]]
"R_Score" = "CalculatedFields.Reading.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"W_Score" = "CalculatedFields.Writing.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"S_Score" = "CalculatedFields.Spelling.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"G_Score" = "CalculatedFields.GrammarAndPunctuation.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"N_Score" = "CalculatedFields.Numeracy.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"R_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"W_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"S_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"G_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"N_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"R_Mean" = "CalculatedFields.Reading.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"W_Mean" = "CalculatedFields.Writing.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"S_Mean" = "CalculatedFields.Spelling.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"G_Mean" = "CalculatedFields.GrammarAndPunctuation.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"N_Mean" = "CalculatedFields.Numeracy.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"R_Participation" = "CalculatedFields.Reading.NAPEventStudentLink.ParticipationCode"
[[fields]]
"W_Participation" = "CalculatedFields.Writing.NAPEventStudentLink.ParticipationCode"
[[fields]]
"S_Participation" = "CalculatedFields.Spelling.NAPEventStudentLink.ParticipationCode"
[[fields]]
"G_Participation" = "CalculatedFields.GrammarAndPunctuation.NAPEventStudentLink.ParticipationCode"
[[fields]]
"N_Participation" = "CalculatedFields.Numeracy.NAPEventStudentLink.ParticipationCode"
[[fields]]
"R_Pathway" = "CalculatedFields.Reading.NAPStudentResponseSet.PathTakenForDomain"
[[fields]]
"W_Pathway" = "CalculatedFields.Writing.NAPStudentResponseSet.PathTakenForDomain"
[[fields]]
"S_Pathway" = "CalculatedFields.Spelling.NAPStudentResponseSet.PathTakenForDomain"
[[fields]]
"G_Pathway" = "CalculatedFields.GrammarAndPunctuation.NAPStudentResponseSet.PathTakenForDomain"
[[fields]]
"N_Pathway" = "CalculatedFields.Numeracy.NAPStudentResponseSet.PathTakenForDomain"
[[fields]]
"R_Stddev" = "CalculatedFields.Reading.NAPStudentResponseSet.DomainScore.ScaledScoreStandardError"
[[fields]]
"W_Stddev" = "CalculatedFields.Writing.NAPStudentResponseSet.DomainScore.ScaledScoreStandardError"
[[fields]]
"S_Stddev" = "CalculatedFields.Spelling.NAPStudentResponseSet.DomainScore.ScaledScoreStandardError"
[[fields]]
"G_Stddev" = "CalculatedFields.GrammarAndPunctuation.NAPStudentResponseSet.DomainScore.ScaledScoreStandardError"
[[fields]]
"N_Stddev" = "CalculatedFields.Numeracy.NAPStudentResponseSet.DomainScore.ScaledScoreStandardError"
[[fields]]
"R_DomainBand" = "CalculatedFields.Reading.NAPStudentResponseSet.DomainScore.StudentDomainBand"
[[fields]]
"W_DomainBand" = "CalculatedFields.Writing.NAPStudentResponseSet.DomainScore.StudentDomainBand"
[[fields]]
"S_DomainBand" = "CalculatedFields.Spelling.NAPStudentResponseSet.DomainScore.StudentDomainBand"
[[fields]]
"G_DomainBand" = "CalculatedFields.GrammarAndPunctuation.NAPStudentResponseSet.DomainScore.StudentDomainBand"
[[fields]]
"N_DomainBand" = "CalculatedFields.Numeracy.NAPStudentResponseSet.DomainScore.StudentDomainBand"
