
[usage]
reportName = "Basic ISR data for input to jurisdictional ISR printing processes"
activated = true
outputFileName = "./out/system_reports/isrPrinting.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"EDID" = "StudentPersonal.LocalId"
[[fields]]
"First Name" = "StudentPersonal.PersonInfo.Name.GivenName"
[[fields]]
"Last Name" = "StudentPersonal.PersonInfo.Name.FamilyName"
[[fields]]
"Year Level" = "CalculatedFields.YrLevel"
[[fields]]
"School Code" = "SchoolInfo.LocalId"
[[fields]]
"School Name" = "SchoolInfo.SchoolName"
[[fields]]
"R_Score" = "CalculatedFields.Reading.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"W_Score" = "CalculatedFields.Writing.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"S_Score" = "CalculatedFields.Spelling.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"G_Score" = "CalculatedFields.GrammarAndPunctuation.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"N_Score" = "CalculatedFields.Numeracy.NAPStudentResponseSet.DomainScore.ScaledScoreValue"
[[fields]]
"R_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"W_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"S_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"G_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"N_Comment" = "CalculatedFields.ISRCommmentPlaceholder"
[[fields]]
"R_Mean" = "CalculatedFields.Reading.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"W_Mean" = "CalculatedFields.Writing.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"S_Mean" = "CalculatedFields.Spelling.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"G_Mean" = "CalculatedFields.GrammarAndPunctuation.NAPTestScoreSummary.DomainNationalAverage"
[[fields]]
"N_Mean" = "CalculatedFields.Numeracy.NAPTestScoreSummary.DomainNationalAverage"
