
[usage]
reportName = "Highlights any differences between the items expected to be presented and those seen by the student"
activated = true
outputFileName = "./out/qa/itemExpectedResponses.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#
[[fields]]
"School" = "CalculatedFields.SchoolId"
[[fields]]
"YrLevel" = "CalculatedFields.YrLevel"
[[fields]]
"Domain" = "CalculatedFields.Domain"
#
# fields above are for report splitting 
#

[[fields]]
"PSI" = "NAPEventStudentLink.PlatformStudentIdentifier"
[[fields]]
"Test" = "NAPTest.TestContent.TestName"
[[fields]]
"Participation Code" = "NAPEventStudentLink.ParticipationCode"
# 
# testlet 1
# 
[[fields]]
"Testlet 1 Name" = "CalculatedFields.ItemExpectedResponses.Testlet.1.TestletName"
[[fields]]
"# Expected Items Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.ExpectedItemsCount"
[[fields]]
"# Correct Items Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.Correct"
[[fields]]
"# Incorrect Items Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.Incorrect"
[[fields]]
"# Not Attempted Items Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.NotAttempted"
[[fields]] # no longer in rrd explicitly, by implication are in expected not found list
"# Not In Path Items testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.NotInPath"
[[fields]]
"Expected Items Not Found Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.ExpectedItemsNotFound"
[[fields]]
"Found Items Not Expected Testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItemsNotExpected"
# 
# testlet 2
# 
[[fields]]
"Testlet 2 Name" = "CalculatedFields.ItemExpectedResponses.Testlet.2.TestletName"
[[fields]]
"# Expected Items Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.ExpectedItemsCount"
[[fields]]
"# Correct Items Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.FoundItems.Correct"
[[fields]]
"# Incorrect Items Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.FoundItems.Incorrect"
[[fields]]
"# Not Attempted Items Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.FoundItems.NotAttempted"
[[fields]] # no longer in rrd explicitly, by implication are in expected not found list
"# Not In Path Items testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.NotInPath"
[[fields]]
"Expected Items Not Found Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.ExpectedItemsNotFound"
[[fields]]
"Found Items Not Expected Testlet 2" = "CalculatedFields.ItemExpectedResponses.Testlet.2.FoundItemsNotExpected"
# 
# testlet 3
# 
[[fields]]
"Testlet 3 Name" = "CalculatedFields.ItemExpectedResponses.Testlet.3.TestletName"
[[fields]]
"# Expected Items Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.ExpectedItemsCount"
[[fields]]
"# Correct Items Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.FoundItems.Correct"
[[fields]]
"# Incorrect Items Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.FoundItems.Incorrect"
[[fields]]
"# Not Attempted Items Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.FoundItems.NotAttempted"
[[fields]] # no longer in rrd explicitly, by implication are in expected not found list
"# Not In Path Items testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.NotInPath"
[[fields]]
"Expected Items Not Found Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.ExpectedItemsNotFound"
[[fields]]
"Found Items Not Expected Testlet 3" = "CalculatedFields.ItemExpectedResponses.Testlet.3.FoundItemsNotExpected"
# 
# testlet 4
# 
[[fields]]
"Testlet 4 Name" = "CalculatedFields.ItemExpectedResponses.Testlet.4.TestletName"
[[fields]]
"# Expected Items Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.ExpectedItemsCount"
[[fields]]
"# Correct Items Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.FoundItems.Correct"
[[fields]]
"# Incorrect Items Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.FoundItems.Incorrect"
[[fields]]
"# Not Attempted Items Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.FoundItems.NotAttempted"
[[fields]] # no longer in rrd explicitly, by implication are in expected not found list
"# Not In Path Items testlet 1" = "CalculatedFields.ItemExpectedResponses.Testlet.1.FoundItems.NotInPath"
[[fields]]
"Expected Items Not Found Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.ExpectedItemsNotFound"
[[fields]]
"Found Items Not Expected Testlet 4" = "CalculatedFields.ItemExpectedResponses.Testlet.4.FoundItemsNotExpected"
