
[usage]
reportName = "(QA) Summary of student distributions accross year-levels and tests with participation data"
activated = true
outputFileName = "./out/qa/qaSchools.csv"

# Order of fields below is left to right order
# columns will appear in final output, can be changed as needed.
# Double brackets required to ensure map is created as array to preserve order
# commenting out a key/value pair will remove that column from the
# final report
#

[[fields]]
"SchoolName" = "SchoolInfo.SchoolName"
[[fields]]
"Sector" = "CalculatedFields.QaSchools.DerivedSector"
[[fields]]
"System" = "CalculatedFields.QaSchools.DerivedSystem"
[[fields]]
"Independent" = "IndependentSchool"
[[fields]]
"Type" = "SchoolType"
[[fields]]
"Local ID" = "SchoolInfo.LocalId"
[[fields]]
"ACARA ID" = "CalculatedFields.QaSchools.SchoolACARAId"
[[fields]]
"State ID" = "StateProvinceId"
[[fields]]
"District" = "SchoolDistrict"
[[fields]]
"Address" = "AddressList.Address"
# 
[[fields]]
"Total Reg. Students" = "CalculatedFields.QaSchools.TotalStudents"
# 
[[fields]]
"Students Reg. yr3" = "CalculatedFields.QaSchools.YearLevel.3.TotalStudents"
[[fields]]
"Students Reg. yr5" = "CalculatedFields.QaSchools.YearLevel.5.TotalStudents"
[[fields]]
"Students Reg. yr7" = "CalculatedFields.QaSchools.YearLevel.7.TotalStudents"
[[fields]]
"Students Reg. yr9" = "CalculatedFields.QaSchools.YearLevel.9.TotalStudents"
[[fields]]
"Students Reg. Test lvl3" = "CalculatedFields.QaSchools.TestLevel.3.TotalStudents"
[[fields]]
"Students Reg. Test lvl5" = "CalculatedFields.QaSchools.TestLevel.5.TotalStudents"
[[fields]]
"Students Reg. Test lvl7" = "CalculatedFields.QaSchools.TestLevel.7.TotalStudents"
[[fields]]
"Students Reg. Test lvl9" = "CalculatedFields.QaSchools.TestLevel.9.TotalStudents"
# 
[[fields]]
"Total Test Attempts" = "CalculatedFields.QaSchools.TotalTestAttempts"
# 
[[fields]]
"Yr 3 G&P" = "CalculatedFields.QaSchools.TestLevel.3.TestDomain.GrammarAndPunctuation.TotalAttempts"
[[fields]]
"Yr 3 Writing" = "CalculatedFields.QaSchools.TestLevel.3.TestDomain.Writing.TotalAttempts"
[[fields]]
"Yr 3 Numeracy" = "CalculatedFields.QaSchools.TestLevel.3.TestDomain.Numeracy.TotalAttempts"
[[fields]]
"Yr 3 Reading" = "CalculatedFields.QaSchools.TestLevel.3.TestDomain.Reading.TotalAttempts"
[[fields]]
"Yr 3 Spelling" = "CalculatedFields.QaSchools.TestLevel.3.TestDomain.Spelling.TotalAttempts"
# 
[[fields]]
"Yr 5 G&P" = "CalculatedFields.QaSchools.TestLevel.5.TestDomain.GrammarAndPunctuation.TotalAttempts"
[[fields]]
"Yr 5 Writing" = "CalculatedFields.QaSchools.TestLevel.5.TestDomain.Writing.TotalAttempts"
[[fields]]
"Yr 5 Numeracy" = "CalculatedFields.QaSchools.TestLevel.5.TestDomain.Numeracy.TotalAttempts"
[[fields]]
"Yr 5 Reading" = "CalculatedFields.QaSchools.TestLevel.5.TestDomain.Reading.TotalAttempts"
[[fields]]
"Yr 5 Spelling" = "CalculatedFields.QaSchools.TestLevel.5.TestDomain.Spelling.TotalAttempts"
# 
[[fields]]
"Yr 7 G&P" = "CalculatedFields.QaSchools.TestLevel.7.TestDomain.GrammarAndPunctuation.TotalAttempts"
[[fields]]
"Yr 7 Writing" = "CalculatedFields.QaSchools.TestLevel.7.TestDomain.Writing.TotalAttempts"
[[fields]]
"Yr 7 Numeracy" = "CalculatedFields.QaSchools.TestLevel.7.TestDomain.Numeracy.TotalAttempts"
[[fields]]
"Yr 7 Reading" = "CalculatedFields.QaSchools.TestLevel.7.TestDomain.Reading.TotalAttempts"
[[fields]]
"Yr 7 Spelling" = "CalculatedFields.QaSchools.TestLevel.7.TestDomain.Spelling.TotalAttempts"
# 
[[fields]]
"Yr 9 G&P" = "CalculatedFields.QaSchools.TestLevel.9.TestDomain.GrammarAndPunctuation.TotalAttempts"
[[fields]]
"Yr 9 Writing" = "CalculatedFields.QaSchools.TestLevel.9.TestDomain.Writing.TotalAttempts"
[[fields]]
"Yr 9 Numeracy" = "CalculatedFields.QaSchools.TestLevel.9.TestDomain.Numeracy.TotalAttempts"
[[fields]]
"Yr 9 Reading" = "CalculatedFields.QaSchools.TestLevel.9.TestDomain.Reading.TotalAttempts"
[[fields]]
"Yr 9 Spelling" = "CalculatedFields.QaSchools.TestLevel.9.TestDomain.Spelling.TotalAttempts"
# 
[[fields]]
"Not Enrolled (X)" = "CalculatedFields.QaSchools.ParticipationCode.X.TotalAttempts"
[[fields]]
"Absent (A)" = "CalculatedFields.QaSchools.ParticipationCode.A.TotalAttempts"
[[fields]]
"Cancelled (C)" = "CalculatedFields.QaSchools.ParticipationCode.C.TotalAttempts"
[[fields]]
"Exempt (E)" = "CalculatedFields.QaSchools.ParticipationCode.E.TotalAttempts"
[[fields]]
"Withdrawn (W)" = "CalculatedFields.QaSchools.ParticipationCode.W.TotalAttempts"
[[fields]]
"Sanctioned Abandon. (S)" = "CalculatedFields.QaSchools.ParticipationCode.S.TotalAttempts"
[[fields]]
"Refused (R)" = "CalculatedFields.QaSchools.ParticipationCode.R.TotalAttempts"
[[fields]]
"Alt Format (F)" = "CalculatedFields.QaSchools.ParticipationCode.F.TotalAttempts"
# 
[[fields]]
"Disruptions" = "CalculatedFields.QaSchools.TotalDisruptions"
# 
# [[fields]]
# "Writing Extracts Y3" = "CalculatedFields.QaSchools.TestLevel.3.TotalExtracts"
# [[fields]]
# "Writing Extracts Y5" = "CalculatedFields.QaSchools.TestLevel.5.TotalExtracts"
# [[fields]]
# "Writing Extracts Y7" = "CalculatedFields.QaSchools.TestLevel.7.TotalExtracts"
# [[fields]]
# "Writing Extracts Y9" = "CalculatedFields.QaSchools.TestLevel.9.TotalExtracts"

