
[usage]
reportName = "XML output per school"
activated = false
# leave the placeholder "dummy" alone
outputFileName = "./out/redacted_xml/dummy"

# Fields in this report are ignored
#
[[fields]]
"School ACARA Id" = "SchoolInfo.ACARAId"

