# This is a sample configuration.

InFolder = "./out/" # (string), in which folder splitter processes report csv files.
TrimColAfterSplit = true # (bool), if true, designated Trim Columns apply to Split result
WalkSubFolders = true # (bool), if true, splitter process every file including the file in sub-folders; otherwise, ignores sub-folder files.

[Trim]
Columns = ["School", "YrLevel", "Domain"] # (string array), which columns to be removed from original csv file.                    
Enabled = true # (bool), turn on/off Trim function.
OutFolder = "./out_trim/" # (string), in which folder trimmed csv files should be output.

[Split]
Enabled = true # (bool), turn on/off Split function.
IgnoreFolder = "./ignore/" # (string), If not empty string, dump unsplittable csv file into this folder. If empty, ignore unsplittable csv files.
OutFolder = "./out_split/" # (string), in which folder split results should be output.
Schema = ["School", "YrLevel"] # (string array), header sequence for splitting. Each header creates its split category folder.            
StrictMode = true # (bool), If true, splittable csv file must have all [Schema] headers. Otherwise, dump it into IgnoreFolder. If false, use partial, sequence [Schema] to do splitting, and IgnoreFolders are also into its own split result path.
