# This is a sample configuration.

InFolder = "./out/" # (string), in which folder splitter processes report csv files.
TrimColAfterSplit = true # (bool), if true, designated Trim Columns apply to Split result
WalkSubFolders = true # (bool), if true, splitter process every file including the file in sub-folders; otherwise, ignores sub-folder files.

[Trim]
Columns = ["School", "YrLevel", "Domain"] # (string array), which columns to be removed from original csv file.      
Enabled = true # (bool), turn on/off Trim function.
OutFolder = "./out/" # (string), in which folder trimmed csv files should be output.

[Split]
Enabled = true # (bool), turn on/off Split function.
OutFolder = "./out_split/" # (string), in which folder split results should be output.
Schema = ["School", "YrLevel"] # (string array), header sequence for splitting. Each header creates its split category folder.
